#!/usr/local/bin/node

var Polynom = require("./Polynom"),
	Solver = require("./Solver"),
	Analyse = require("./Analyse")
	arg = (function () {

		var argv = process.argv;
		
		if (argv.length != 3) {
			console.log ("Error: Wrong number of arguments");
			process.exit(1);
		}
		
		var noSpace = argv[2].replace(/[\s]+/g, "")
								.replace(/\+\-/g, "-")
								.replace(/\-\+/g, "-")
								.replace(/\-\-/g, "+")
								.replace(/\+\+/g, "+")
								.replace(/x/g, "X")
								.replace(/x²/ig, "X^2")
								.replace(/−/g, "-"),
			equal = noSpace.split(/=/);
		
		if (equal.length != 2) {
			console.log("Syntax Error");
			process.exit(1);
		}

		

		if (equal[0][0] != "-" && equal[0][0] != "+")
			equal[0] = "+" + equal[0];
		if (equal[1][0] != "-" && equal[1][0] != "+")
			equal[1] = "+" + equal[1];
			
	

		equal[1] = equal[1].replace(/\+/g, "moin")
							.replace(/\-/g, "plus")
							.replace(/moin/g, "-")
							.replace(/plus/g, "+");

		noSpace = equal.join("") + "=0";
		noSpace = noSpace.replace(/\+X/g, "+1X")
							.replace(/\-X/g, "-1X")
							.replace(/X\^/g, "x^")
							.replace(/X/g, "x^1")
							.replace(/x/g, "X");

		return (noSpace);
	})(),

	p = new Polynom(arg);


if (arg == false) {
	
}
var elem = arg.split(/[\+\-=]/g);
	
elem.shift();
elem.push("end");
for (i = 0; i < elem.indexOf("end"); i++) {
	if (elem[i] == '' && i < elem.indexOf("end") - 1) {
		console.log("Syntax Error");
		process.exit(1);		
	}
}

for (i = 0; i < arg.length; i++) {
	if ((arg[i] < '0' || arg[i] > '9')
			&& arg[i] != '-'
			&& arg[i] != '+'
			&& arg[i] != 'x'
			&& arg[i] != 'X'
			&& arg[i] != '='
			&& arg[i] != '^'
			&& arg[i] != '.'
			&& arg[i] != '*') {
		console.log("Syntax Error");
		process.exit(1);		
	}
}


p.reduce();
p.merge();
p.degreeMax();
console.log("Reduced form: " + p.goodStr);
console.log("Polynomial degree: " + p.degree + "\n");
Solver.solve(p);
Analyse.all(p);